from testframework import *

LEFT = 1
RIGHT = 2

POS_LEFT_FREE   = 11.0
POS_LEFT_UP     = 5.0
POS_LEFT_DOWN   = 2.9
POS_RIGHT_FREE  = 3.5
POS_RIGHT_UP    = 9.5
POS_RIGHT_DOWN  = 11.4
PWM_FREQUENCY   = 50

PIN_BUTTON_LEFT = OUT3
PIN_BUTTON_RIGHT= OUT5
PIN_3V3_SUPPLY  = AIN1
PIN_LED         = AIN3
PIN_PWM_OUT     = IN7
