name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build STM32CubeIde project
      uses: xanderhendriks/action-build-stm32cubeide@v11.0
      with:
        project-path: '.'
        project-target: 'Testplatine'
      env:
        ENV_VERSION_MAJOR: 1
        ENV_VERSION_MINOR: 0
        ENV_VERSION_BUGFIX: 0

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: Debug/Testplatine.bin

  remote-test:
    needs: build
    runs-on: [self-hosted, linux]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./firmware

    - name: Unzip artifact content
      run: unzip -o ./firmware/*.zip -d ./firmware/

    - name: Show files in firmware directory
      run: ls ./firmware

    - name: Flash firmware
      run: st-flash write ./firmware/Testplatine.bin 0x8000000

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Test
      env:
        test-path: "Tests"
      run: |
        sudo docker build -t test-executor https://github.com/emintes/action-test-executor.git#main
        sudo docker run --name test-container --device=/dev --privileged -v "${{ github.workspace }}:/workspace/repo" test-executor ${{ env.test-path }}
        sudo docker cp test-container:/workspace/Testreport.html ./Tests/Testreport.html
        sudo docker rm test-container

    - name: Upload Testreport artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Testreport
        path: Tests/Testreport.html
