name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build STM32CubeIde project
      uses: xanderhendriks/action-build-stm32cubeide@v11.0
      with:
        project-path: '.'
        project-target: 'Testplatine'
      env:
        ENV_VERSION_MAJOR: 1
        ENV_VERSION_MINOR: 0
        ENV_VERSION_BUGFIX: 0

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: Debug/Testplatine.bin

  remote-test:
    needs: build
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./firmware

    - name: Run Test
      env:
        test-project-folder: "Tests"
      run: |
        docker pull emintes/testplattform:arm64
        docker run --rm --name test-container --device=/dev --privileged \
          -v "${{ github.workspace }}:/workspace/repo" \
          -e TEST_PROJECT_FOLDER="${{ env.test-project-folder }}" \
          -e EXTRA_COMMANDS="${{ env.extra-commands }}" \
          emintes/testplattform:arm64

    - name: Upload Testreport artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Testreport
        path: Tests/Reports/Testreport.html
